version: "3.9"

services:
  node-server:
    image: node-server:prod
    build:
      context: .
      target: prod
    container_name: node-server
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "5000:5000"
    networks:
      - my_network
    volumes:
      - ./:/app:ro
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - my_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ${MONGO_PATH}:/data/db

networks:
  my_network:
    external: true
