version: "3.9"

services:
  node-server:
    image: node-server:dev
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: dev
    container_name: node-server
    environment:
      - PORT=5000
      - NODE_ENV=development
    ports:
      - "5000:5000"
    networks:
      - my_network
    volumes:
      - ../:/app:ro
      - /app/node_modules
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - my_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ${MONGO_PATH}:/data/db

networks:
  my_network:
    external: true
